### ISSUE TITLE
Mod fails to load

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [InJir69/create_brass_coated#13]
On trying to add this mod to my modded 1.18.2 Minecraft, it crashed in Forge.  So I created a test instance of my mod order which contained nothing but create, this mod, and all the library mods needed by my other mods.  It still crashed in Forge.  I'd like to use this mod, but it's not essential to me.  On the other hand, knowing why it crashed might help you in your development of this mod, so here I am, and here's the Forge crash report:

<details><summary>Forge Crash Report Details</summary>
<p>
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.2.10-universal.jar%23128!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:170) ~[forge-1.18.2-40.2.10-universal.jar%23128!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:557) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:flytre_lib.mixins.json:event.MinecraftClientMixin,pl:mixin:APP:ding.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:puzzleslib.forge.mixins.json:client.MinecraftForgeMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:397) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:551) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:flytre_lib.mixins.json:event.MinecraftClientMixin,pl:mixin:APP:ding.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:puzzleslib.forge.mixins.json:client.MinecraftForgeMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:879) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:flytre_lib.mixins.json:event.MinecraftClientMixin,pl:mixin:APP:ding.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:puzzleslib.forge.mixins.json:client.MinecraftForgeMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:flytre_lib.mixins.json:event.MinecraftClientMixin,pl:mixin:APP:ding.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:puzzleslib.forge.mixins.json:client.MinecraftForgeMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.10.jar%2352!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.injir.create_brass_coated.Create_Brass_Coated.<clinit>(Create_Brass_Coated.java:27) ~[create_brass_coated-0.2.2.1-1.18.2.jar%2369!/:0.2.2.1-1.18.2] {re:classloading}
-- MOD create_brass_coated --
Details:
	Mod File: /H:/Program Files (32-Bit)/MultiMC/instances/1.18.2 Test/.minecraft/mods/create_brass_coated-0.2.2.1-1.18.2.jar
	Failure message: Create: Brass Coated (create_brass_coated) has failed to load correctly
		java.lang.NoSuchMethodError: 'com.tterrag.registrate.util.nullness.NonNullSupplier com.simibubi.create.foundation.data.CreateRegistrate.lazy(java.lang.String)'
	Mod Version: 0.2.2.1-1.18.2
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchMethodError: 'com.tterrag.registrate.util.nullness.NonNullSupplier com.simibubi.create.foundation.data.CreateRegistrate.lazy(java.lang.String)'
Stacktrace:
	at com.injir.create_brass_coated.Create_Brass_Coated.<clinit>(Create_Brass_Coated.java:27) ~[create_brass_coated-0.2.2.1-1.18.2.jar%2369!/:0.2.2.1-1.18.2] {re:classloading}
	at jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?] {}
	at jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160) ~[?:?] {}
	at jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300) ~[?:?] {}
	at jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103) ~[?:?] {}
	at jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200) ~[?:?] {}
	at java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:547) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:497) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.10.jar%23125!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.10.jar%23124!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 20.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 3237908288 bytes (3087 MiB) / 8589934592 bytes (8192 MiB) up to 25769803776 bytes (24576 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600G with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.89
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon RX 7900 XTX
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x744c
	Graphics card #0 versionInfo: DriverVersion=31.0.14051.1000
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 65405.95
	Virtual memory used (MB): 49421.06
	Swap memory total (MB): 32768.00
	Swap memory used (MB): 2994.18
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms8192m -Xmx24576m
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@3.12.0
		lowcodefml@null
		kotori_scala@2.13.10-build-12
	Mod List: 
		dynamiclightsreforged-1.18.2_v1.3.3.jar           |Rubidium Dynamic Lights       |dynamiclightsreforged         |1.18.2_v1.3.3       |COMMON_SET|Manifest: NOSIGNATURE
		CyclopsCore-1.18.2-1.17.5.jar                     |Cyclops Core                  |cyclopscore                   |1.17.5              |COMMON_SET|Manifest: NOSIGNATURE
		radium-0.7.10.jar                                 |Radium                        |radium                        |0.7.10              |COMMON_SET|Manifest: NOSIGNATURE
		Kiwi-1.18.2-forge-6.1.4.jar                       |Kiwi                          |kiwi                          |6.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.7-forge-mc1.18.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.7               |COMMON_SET|Manifest: NOSIGNATURE
		paucal-forge-1.18.2-0.4.7.jar                     |PAUCAL                        |paucal                        |0.4.7               |COMMON_SET|Manifest: NOSIGNATURE
		no_null_processors_forge-2.0.2+1.18.1.jar         |No Null Processors            |no_null_processors            |2.0.2+1.18.1        |COMMON_SET|Manifest: NOSIGNATURE
		Cucumber-1.18.2-5.1.4.jar                         |Cucumber Library              |cucumber                      |5.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		OreLibrary-1.18.2-1.0.2.jar                       |OreLibrary                    |orelibrary                    |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		KazFraPrimeCore+1.2+1.18.2.jar                    |KazFraPrimeCore               |kazfraprimecore               |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		knightcore-1.18.2-1.1.jar                         |Knightcore                    |knightcore                    |1.18.2-1.1          |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.18.2-forge-10.2.1.1005.jar                  |Just Enough Items             |jei                           |10.2.1.1005         |COMMON_SET|Manifest: NOSIGNATURE
		libraryferret-forge-1.18.2-4.0.0.jar              |Library ferret                |libraryferret                 |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		caelus-forge-1.18.1-3.0.0.2.jar                   |Caelus API                    |caelus                        |1.18.1-3.0.0.2      |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedcore-1.18.2-0.5.80.376.jar           |Sophisticated Core            |sophisticatedcore             |1.18.2-0.5.80.376   |COMMON_SET|Manifest: NOSIGNATURE
		rubidium-0.5.6.jar                                |Rubidium                      |rubidium                      |0.5.6               |COMMON_SET|Manifest: NOSIGNATURE
		bdlib-1.19.3.7-mc1.18.2.jar                       |BdLib                         |bdlib                         |1.19.3.7            |COMMON_SET|Manifest: NOSIGNATURE
		ForgeEndertech-1.18.2-9.0.7.0-build.1490.jar      |ForgeEndertech                |forgeendertech                |9.0.7.0             |COMMON_SET|Manifest: NOSIGNATURE
		integrated_api_forge-1.2.7+1.18.2.jar             |Integrated API                |integrated_api                |1.2.7+1.18.2        |COMMON_SET|Manifest: NOSIGNATURE
		configured-2.0.1-1.18.2.jar                       |Configured                    |configured                    |2.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		YungsApi-1.18.2-Forge-2.2.9.jar                   |YUNG's API                    |yungsapi                      |1.18.2-Forge-2.2.9  |COMMON_SET|Manifest: NOSIGNATURE
		LibX-1.18.2-3.2.18.jar                            |LibX                          |libx                          |1.18.2-3.2.18       |COMMON_SET|Manifest: NOSIGNATURE
		feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.ja|Feature NBT Deadlock Be Gone  |feature_nbt_deadlock_be_gone  |2.0.0+1.18.2        |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.18.2-13.3.56.jar                |Bookshelf                     |bookshelf                     |13.3.56             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		mcjtylib-1.18-6.0.20.jar                          |McJtyLib                      |mcjtylib                      |1.18-6.0.20         |COMMON_SET|Manifest: NOSIGNATURE
		rftoolsbase-1.18-3.0.12.jar                       |RFToolsBase                   |rftoolsbase                   |1.18-3.0.12         |COMMON_SET|Manifest: NOSIGNATURE
		setworldspawnpoint-1.18.2-3.1.jar                 |Set World Spawn Point         |setworldspawnpoint            |3.1                 |COMMON_SET|Manifest: NOSIGNATURE
		catalogue-1.6.2-1.18.2.jar                        |Catalogue                     |catalogue                     |1.6.2               |COMMON_SET|Manifest: NOSIGNATURE
		balm-3.2.6.jar                                    |Balm                          |balm                          |3.2.6               |COMMON_SET|Manifest: NOSIGNATURE
		FpsReducer2-forge-1.18.2-2.0.jar                  |FPS Reducer                   |fpsreducer                    |1.18.2-2.0          |COMMON_SET|Manifest: NOSIGNATURE
		CraftTweaker-forge-1.18.2-9.1.209.jar             |CraftTweaker                  |crafttweaker                  |9.1.209             |COMMON_SET|Manifest: NOSIGNATURE
		rubidium_extras-1.18.2_v1.3.2.jar                 |Rubidium Extras               |rubidium_extras               |1.18.2_v1.3.2       |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-6.5.102-forge.jar                    |Cloth Config v4 API           |cloth_config                  |6.5.102             |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.2-40.2.10-universal.jar                |Forge                         |forge                         |40.2.10             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		shetiphiancore-forge-1.18.2-3.10.16.jar           |ShetiPhian-Core               |shetiphiancore                |3.10.16             |COMMON_SET|Manifest: NOSIGNATURE
		inzheFoPCore-v.3.0.0-1.18.2.jar                   |inzheFoPs Core                |inzhefopcore                  |3.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		ExperienceBugFix-1.18-1.38.0.2.jar                |Experience Bug Fix            |experiencebugfix              |1.38.0.2            |COMMON_SET|Manifest: NOSIGNATURE
		structure_gel-1.18.2-2.4.7.jar                    |Structure Gel API             |structure_gel                 |2.4.7               |COMMON_SET|Manifest: NOSIGNATURE
		selene-1.18.2-1.17.9.jar                          |Selene                        |selene                        |1.18.2-1.17.9       |COMMON_SET|Manifest: NOSIGNATURE
		flytre_lib-1.18.2-1.8.2-forge.jar                 |FlytreLib                     |flytre_lib                    |1.8.2               |COMMON_SET|Manifest: NOSIGNATURE
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		TerraBlender-forge-1.18.2-1.2.0.126.jar           |TerraBlender                  |terrablender                  |1.2.0.126           |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedbackpacksvh-1.18.2-1.0.5.13.jar      |Sophisticated Backpacks Vault |sophisticatedbackpacksvh      |1.18.2-1.0.5.13     |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.18.2-3.18.57.888.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.2-3.18.57.888  |COMMON_SET|Manifest: NOSIGNATURE
		sebastrnlib-1.0.2.jar                             |Sebastrn Lib                  |sebastrnlib                   |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		create_brass_coated-0.2.2.1-1.18.2.jar            |Create: Brass Coated          |create_brass_coated           |0.2.2.1-1.18.2      |ERROR     |Manifest: NOSIGNATURE
		Jade-1.18.2-forge-5.3.0.jar                       |Jade                          |jade                          |5.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		material_elements_1.18.2-3.9.0.jar                |Material Elements             |material_elements             |3.9.0               |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.11-forge-mc1.18.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.11              |COMMON_SET|Manifest: NOSIGNATURE
		Ding-1.18.2-Forge-1.4.1.jar                       |Ding                          |ding                          |1.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		RecipesLibrary-1.18.2-2.0.0.jar                   |Recipes Library               |recipes_lib                   |2.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		kffmod-3.12.0.jar                                 |Kotlin For Forge              |kotlinforforge                |3.12.0              |COMMON_SET|Manifest: NOSIGNATURE
		ManyIdeasCore-1.18.2-1.4.1.jar                    |ManyIdeas Core                |manyideas_core                |1.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		Iceberg-1.18.2-forge-1.0.49.jar                   |Iceberg                       |iceberg                       |1.0.49              |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.9.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.9.1      |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-forge-1.18.2-0.6.9-101.jar               |Flywheel                      |flywheel                      |0.6.9-101           |COMMON_SET|Manifest: NOSIGNATURE
		create-1.18.2-0.5.1.c.jar                         |Create                        |create                        |0.5.1.c             |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.18.2-71.1.jar                         |Patchouli                     |patchouli                     |1.18.2-71.1         |COMMON_SET|Manifest: NOSIGNATURE
		blockui-1.18.2-0.0.71-ALPHA.jar                   |UI Library Mod                |blockui                       |1.18.2-0.0.71-ALPHA |COMMON_SET|Manifest: NOSIGNATURE
		oculus-mc1.18.2-1.6.4.jar                         |Oculus                        |oculus                        |1.6.4               |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.18.2-6.65.jar                        |Collective                    |collective                    |6.65                |COMMON_SET|Manifest: NOSIGNATURE
		polymorph-forge-1.18.2-0.49.jar                   |Polymorph                     |polymorph                     |1.18.2-0.49         |COMMON_SET|Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |COMMON_SET|Manifest: NOSIGNATURE
		libnonymous-2.1.0.jar                             |libnonymous                   |libnonymous                   |2.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		coroutil-1.18.2-1.2.45.jar                        |CoroUtil                      |coroutil                      |1.18.2-1.2.45       |COMMON_SET|Manifest: NOSIGNATURE
		architectury-4.11.93-forge.jar                    |Architectury                  |architectury                  |4.11.93             |COMMON_SET|Manifest: NOSIGNATURE
		PuzzlesLib-v3.4.6-1.18.2-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.4.6               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		asynclocator-1.18.2-1.1.0.jar                     |Async Locator                 |asynclocator                  |1.18.2-1.1.0        |COMMON_SET|Manifest: NOSIGNATURE
		polylib-forge-1801.0.2-build.13.jar               |PolyLib                       |polylib                       |1801.0.2-build.13   |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.18-3.0.57.jar                    |GeckoLib                      |geckolib3                     |3.0.57              |COMMON_SET|Manifest: NOSIGNATURE
		themillmanlib-1.18.2-0.0.14.jar                   |TheMillman Lib                |themillmanlib                 |1.18.2-0.0.14       |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: b4de5f53-f3aa-4227-beab-8e12e1a72cb9
	Flywheel Backend: GL33 Instanced Arrays
	FML: 40.2
	Forge: net.minecraftforge:40.2.10
</p>
</details>

**Comment by KajesLorian** [comment]
This is probably because it's not compatible with Create 0.5.1a, which made a few changes that broke all create addons.
