### ISSUE TITLE
Mod causes server to fail to start

### ISSUE THREAD

**Issue by VenoPhage** [InJir69/create_brass_coated#4]
Forge: 43.2.3
MC: 1.19.2
LOGS: 
[latest.log](https://github.com/InJir69/create_brass_coated/files/10593603/latest.log)

**Comment by SrRapero720** [comment]
Same issue

**Comment by InJir69** [comment]
I tried to fix it earlier, later I will sit and understand how to fix it

**Comment by DeltaWolf7** [comment]
If it helps.

`-- MOD create_brass_coated --
[14.02 21:58:54] [Server] Details:
[14.02 21:58:54] [Server] 	Caused by java.lang.ExceptionInInitializerError
[14.02 21:58:54] [Server] 		at com.injir.create_brass_coated.BrassPonder.register(BrassPonder.java:26) ~[create_brass_coated-0.2.2-1.19.2.jar%23649!/:0.2.2-1.19.{re:classloading}
[14.02 21:58:54] [Server] 		at com.injir.create_brass_coated.Create_Brass_Coated.init(Create_Brass_Coated.java:54) ~[create_brass_coated-0.2.2-1.19.2.jar%23649!/:0.2.2-1.19.{re:classloading}
[14.02 21:58:54] [Server] 		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2351!/:?] {}
[14.02 21:58:54] [Server] 		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2351!/:?] {}
[14.02 21:58:54] [Server] 		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
[14.02 21:58:54] [Server] 		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
[14.02 21:58:54] [Server] 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.2-43.2.4.jar%231005!/:?] {}
[14.02 21:58:54] [Server] 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19.2-43.2.4.jar%231004!/:?] {}
[14.02 21:58:54] [Server] 		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
[14.02 21:58:54] [Server] 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
[14.02 21:58:54] [Server] 		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
[14.02 21:58:54] [Server] 		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
[14.02 21:58:54] [Server] 		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
[14.02 21:58:54] [Server] 		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
[14.02 21:58:54] [Server] 		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
[14.02 21:58:54] [Server] 	Mod File/mods/create_brass_coated-0.2.2-1.19.2.jar
[14.02 21:58:54] [Server] 	Failure messageCreate: Brass Coated (create_brass_coated) encountered an error during the common_setup event phase
[14.02 21:58:54] [Server] 		java.lang.ExceptionInInitializerErrornull
[14.02 21:58:54] [Server] 	Mod Version0.2.2-1.19.2
[14.02 21:58:54] [Server] 	Mod Issue URLNOT PROVIDED
[14.02 21:58:54] [Server] 	Exception messagejava.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER`

**Comment by SrRapero720** [comment]
Current error is related to use ClientLevel and i see is caused by Ponders, ponders are client only
so probably you only need to do is add a `@OnlyIn(Dist.CLIENT)` over all ponder methods/classes

**Comment by FullMetalMaster** [comment]
its defiantly the mod and it sucks bc i really wanted to use this

**Comment by FullMetalMaster** [comment]
its the lastest verion to same crash on start up on servers

**Comment by oguh43** [comment]
yep

**Comment by InJir69** [comment]
fixed

**Comment by oguh43** [comment]
> fixed

Commit?

**Comment by oguh43** [comment]
Also thanks :)
